PREL-166 add proxy support
percona/percona-repositories pull request #95
Opened 2021-12-09 16:20 UTC by vorsel

2021-12-13 05:26 UTC, EvgeniyPatlan requested changes

2021-12-13 05:26 UTC, EvgeniyPatlan commented on scripts/percona-release.sh
> +CURL_EXEC=( curl )
what avout using absolute path?

2021-12-13 05:26 UTC, EvgeniyPatlan commented on scripts/percona-release.sh
> +      if [[ ! -f /etc/apt/apt.conf.d/99-percona-release ]] || ! grep -Rq "${_proxyline}" /etc/; then
brackets are missed

2021-12-14 15:14 UTC, vorsel commented on scripts/percona-release.sh
> +CURL_EXEC=( curl )
done

2021-12-14 15:14 UTC, vorsel commented on scripts/percona-release.sh
> +      if [[ ! -f /etc/apt/apt.conf.d/99-percona-release ]] || ! grep -Rq "${_proxyline}" /etc/; then
done

2021-12-15 13:35 UTC, AgileStas approved these changes
These changes should work, so approving them.

However, I think that original issue was created with wrong assumptions. Please see https://about.gitlab.com/blog/2021/01/27/we-need-to-talk-no-proxy/ and curl commit https://github.com/curl/curl/blob/30e7641d7d2eb46c0b67c0c495a0ea7e52333ee2/lib/url.c#L2250-L2261
So, the only change that is needed, is to set http_proxy to HTTP_PROXY when the first one is unset and the second one is set.
Also, I'm not sure if setting permanent proxy for the repository based on env variable is a good idea. Think about location-dependent proxy: one for workplace, another one during traveling, etc.)

2022-04-27 05:19 UTC, adivinho approved these changes

2023-04-19 12:52 UTC, EvgeniyPatlan approved these changes

2023-05-01 09:50 UTC, merged